const elementoResposta = document.querySelector("#resposta")
const inputPergunta = document.querySelector("#inputPergunta")
const buttonPerguntar = document.querySelector('#buttonPerguntar')
const respostas = [
    "Certeza!",
  "Não tenho tanta certeza.",
  "É decididamente assim.",
  "Não conte com isso.",
  "Sem dúvidas!",
  "Pergunte novamente mais tarde.",
  "Sim, definitivamente!",
  "Minha resposta é não.",
  "Você pode contar com isso.",
  "Melhor não te dizer agora.",
  "A meu ver, sim.",
  "Minhas fontes dizem não.",
  "Provavelmente.",
  "Não é possível prever agora.",
  "Perspectiva boa.",
  "As perspectivas não são tão boas.",
  "Sim.",
  "Concentre-se e pergunte novamente.",
  "Sinais apontam que sim.",
  "Minha pika.",
  "Senta ni mim xerecao.",
  "vai caga.", "Absolutamente... não sei.",
  "A lua diz sim, mas eu digo não.",
  "A resposta sopra com o vento.",
  "Acho que sim, mas verifique novamente.",
  "Adivinhe... Acertou, não sei!",
  "Agora não posso responder, estou em uma reunião.",
  "Apenas se os porcos voarem.",
  "As estrelas estão alinhadas... para outra pergunta.",
  "Até meu cachorro concorda que sim.",
  "Bem, depende da fase da lua.",
  "Claro! Ou não... Talvez?",
  "Com certeza, talvez.",
  "Como diz minha avó: 'Depende'.",
  "Deixe-me terminar meu café e eu te digo.",
  "Definitivamente... talvez.",
  "Depende do seu signo do zodíaco.",
  "Depende se a galinha atravessou a rua.",
  "Desculpe, estou de folga hoje.",
  "Difícil dizer, estou distraído com pizza.",
  "E a resposta mágica é... tente outra vez.",
  "E por que você quer saber?",
  "Ei, isso é segredo!",
  "Em dias de chuva, a resposta é sim.",
  "Em um universo paralelo, a resposta é clara.",
  "Espere, estou processando...",
  "Estou vendo um... talvez.",
  "Estou vendo uma grande... dúvida aqui.",
  "Eu diria sim, mas sou apenas um conjunto de respostas.",
  "Eu não apostaria nisso.",
  "Eu perguntaria novamente mais tarde.",
  "Eu preciso de mais café para responder.",
  "Eu queria dizer sim, mas meu coração diz não.",
  "Faça uma dança da chuva e pergunte de novo.",
  "Hum... Vou consultar os astros.",
  "Isso é um mistério até para mim.",
  "Isso parece incerto.",
  "Isso soa como uma pergunta para amanhã.",
  "Meu conselho é: não conte com isso.",
  "Meu gato disse que sim.",
  "Meu gato disse que não.",
  "Meu sexto sentido diz não.",
  "Não acredite em tudo que você lê.",
  "Não aposte nisso.",
  "Não consigo ver claramente agora.",
  "Não conte comigo para isso.",
  "Não estou autorizado a revelar essa resposta.",
  "Não ouvi a pergunta, pode repetir?",
  "Não posso dizer agora, estou de férias.",
  "Não posso prever agora, estou em horário de almoço.",
  "Não sei, mas espero que sim.",
  "Não sei, estou em modo de economia de energia.",
  "Não, a menos que o destino intervenha.",
  "Não, mas um milagre sempre pode acontecer.",
  "Não, mas isso não significa que você não deva tentar.",
  "Não, mas não desista!",
  "Não, mas não perca a esperança.",
  "Não, mas sonhar é sempre bom.",
  "Não, mas tenho um bom pressentimento sobre isso.",
  "Não, mas você sempre pode mudar isso.",
  "Não, definitivamente, talvez.",
  "Não, exceto nos dias que terminam com 'Y'.",
  "Não, mas você pode me fazer mudar de ideia.",
  "Não, não, e não. Talvez sim.",
  "Não, não e não. Mas quem sabe?",
  "Não, só na terça-feira.",
  "Nem em seus sonhos mais loucos.",
  "Nem eu sei a resposta para isso.",
  "Nem o Google pode responder isso.",
  "Nem todos os segredos devem ser revelados.",
  "Nossos destinos estão entrelaçados... com incertezas.",
  "O destino ainda não decidiu.",
  "O futuro é nebuloso, tente de novo.",
  "O futuro parece... confuso.",
  "O que você acha?",
  "Olhei no fundo da minha xícara de café e ainda não sei.",
  "Os astros estão silenciosos sobre isso.",
  "Os deuses ainda não me disseram.",
  "Parece bom... mas não posso prometer.",
  "Parece que não.",
  "Parece que sim, mas sem garantias.",
  "Pergunta difícil, tenta outra.",
  "Pergunte de novo amanhã.",
  "Pergunte de novo quando as estrelas alinharem.",
  "Pergunte de novo, não estava prestando atenção.",
  "Pode ser que sim, pode ser que não.",
  "Possivelmente, mas não aposte nisso.",
  "Provavelmente não, mas sonhos podem se tornar realidade.",
  "Provavelmente não, mas você nunca sabe.",
  "Provavelmente não, mas... surpresas acontecem.",
  "Provavelmente sim, mas não me cobra depois.",
  "Quando porcos voarem, talvez.",
  "Que a sorte esteja a seu favor.",
  "Que pergunta interessante... próxima!",
  "Quem sabe no próximo ano.",
  "Quem sabe, quem sabe...",
  "Só em dias que terminam com 'Y'.",
  "Só no dia de São Nunca.",
  "Só se os anjos cantarem.",
  "Só se os peixes voarem.",
  "Só se os planetas se alinharem.",
  "Só se você acreditar!",
  "Só um momento, estou consultando os oráculos.",
  "Talvez em um universo alternativo.",
  "Talvez no mundo da fantasia.",
  "Talvez, mas não conte com isso.",
  "Talvez, mas não segure a respiração.",
  "Talvez, mas você não vai gostar da resposta.",
  "Talvez, se as estrelas permitirem.",
  "Talvez, se você for muito, muito legal.",
  "Talvez. Quer apostar?",
  "Tente novamente mais tarde, estou ocupado agora.",
  "Vai ser difícil, mas não impossível.",
  "Vamos deixar essa resposta para o universo.",
  "Vamos ver o que acontece.",
  "Você acredita em milagres?",
  "Você não quer saber a resposta.",
  "Você só saberá se tentar.",
  "A resposta está além do meu alcance.",
  "A resposta está dançando em algum lugar.",
  "A sabedoria do universo diz... talvez.",
  "A vida é incerta e essa resposta também.",
  "Acho que a sorte está do seu lado.",
  "Acho que é hora de jogar uma moeda.",
  "Ainda estou calculando a resposta.",
  "Alguém disse sim, mas não fui eu.",
  "Alguém lá em cima sabe, mas eu não.",
  "Antes, me diga os números da loteria.",
  "As chances são... eu realmente não sei.",
  "As ondas cósmicas estão confusas.",
  "As respostas estão no vento.",
  "As estrelas estão em silêncio hoje.",
  "Até os sábios estão confusos com essa.",
  "Atire uma flecha e veja onde cai.",
  "Bem, isso é um enigma.",
  "Bola de cristal diz: 'Talvez mais tarde.'",
  "Caiu na rede é peixe... ou não.",
  "Certeza absoluta? Nem tanto.",
  "Chances são como biscoitos, quebráveis.",
  "Coloque isso no gelo e pergunte depois.",
  "Com uma pitada de sorte, talvez.",
  "Consultarei os espíritos para você.",
  "Deixe a poeira baixar e pergunte novamente.",
  "Deixe que os dados decidam.",
  "Depende da cor do céu.",
  "Depende da direção do vento.",
  "Depende da sua determinação.",
  "Depende de quantas estrelas estão visíveis.",
  "Depende do alinhamento planetário.",
  "Depende do humor dos deuses.",
  "Depende se o sol nascer amanhã.",
  "Deveria te dizer, mas esqueci.",
  "Diga-me primeiro, qual é o seu signo?",
  "Diz a lenda que a resposta é sim.",
  "Dizem que sim, mas eu digo não sei.",
  "E se eu disser sim, você acredita?",
  "E se fosse sim? E se fosse não?",
  "E se te dissesse que a resposta é um mistério?",
  "É hora de consultar a bola 8.",
  "É mais complicado do que parece.",
  "É um segredo muito bem guardado.",
  "É uma pergunta para os deuses.",
  "Elas dizem sim, eles dizem não.",
  "Em um mundo perfeito, a resposta é sim.",
  "Em um mundo perfeito, seria um sim claro.",
  "Em um universo paralelo, com certeza.",
  "Em um universo paralelo, definitivamente sim.",
  "Em uma galáxia distante, talvez.",
  "Em uma galáxia muito, muito distante... sim.",
  "Encontre a resposta nas estrelas.",
  "Enquanto isso, em outro universo...",
  "Espera aí, deixe-me checar minha bola de cristal.",
  "Espera, estou tentando ler os sinais.",
  "Está escrito nas estrelas... ou não.",
  "Estou vendo uma luz no fim do túnel.",
  "Estou vendo algo... nebuloso.",
  "Estou vendo... ah, é só poeira.",
  "Estrelas dizem sim, cartas dizem não.",
  "Eu diria que sim, mas quem sou eu?",
  "Eu diria sim, mas minha bola de cristal quebrou.",
  "Eu não sou vidente, mas diria que sim.",
  "Eu preferiria não dizer.",
  "Eu queria dizer sim, mas não posso.",
  "Eu realmente gostaria de saber também.",
  "Eu teria que consultar os anciãos.",
  "Eu vou consultar minha bola de cristal.",
  "Faça uma pergunta mais fácil, por favor.",
  "Fale comigo na próxima lua cheia.",
  "Fale comigo quando Mercúrio não estiver retrógrado.",
  "Feche os olhos e a resposta aparecerá.",
  "Feche os olhos e imagine a resposta.",
  "Fique atento aos sinais.",
  "Fique atento, a resposta está chegando.",
  "Isso exigiria uma bola de cristal.",
  "Isso me parece um mistério.",
  "Isso é algo que o tempo dirá.",
  "Isso é um mistério até para mim.",
  "Isso é um segredo que nem eu sei.",
  "Isso parece uma pergunta para seu coração.",
  "Isso soa como um talvez.",
  "Jogue uma moeda e descubra.",
  "Lance os dados e veja o resultado.",
  "Lance os dados, a resposta está neles.",
  "Leia as folhas de chá para a resposta.",
  "Me dê um minuto, estou pensando...",
  "Me pergunte amanhã e eu talvez saiba.",
  "Me pergunte na próxima semana.",
  "Melhor jogar uma moeda para decidir.",
  "Melhor não estragar a surpresa.",
  "Melhor perguntar a um mágico.",
  "Melhor você não saber agora.",
  "Minha bola de cristal está em manutenção.",
  "Minha bola de cristal está embaçada.",
  "Minha bola de cristal está nebulosa.",
  "Minha bola de cristal não está funcionando.",
  "Minha bola de cristal precisa de pilhas novas.",
  "Minha bola de cristal quebrou, desculpe.",
  "Minha bola de cristal está de férias.",
  "Minha intuição diz que sim.",
  "Minha resposta é tão nebulosa quanto sua pergunta.",
  "Não apostaria todas as minhas fichas nisso.",
  "Não conte com isso, mas quem sabe?",
  "Não conte com isso, mas... talvez.",
  "Não conte com isso, mas... você decide.",
  "Não é dia de dar respostas certeiras.",
  "Não estou me sentindo muito profético hoje.",
  "Não faço ideia, mas estou torcendo por você.",
  "Não posso te dizer, seria trapacear.",
  "Não posso te dizer, é um segredo.",
  "Não posso te dizer, mas estou torcendo.",
  "Não posso te dizer, mas estou torcendo por você.",
  "Não posso te dizer, é contra as regras.",
  "Não sei, mas estou torcendo por você.", "Não tenho certeza, mas estou torcendo por você.",
]

// Clicar em fazer pergunta
function fazerPergunta() {
    if(inputPergunta.value == "") {
        alert("Digite sua pergunta")
        return
    }

    buttonPerguntar.setAttribute("disabled", true)

    const pergunta = "<div>" + inputPergunta.value + "</div>"
    let totalRespostas = respostas.length;
    let numeroAleatorio;

    // Example: Check for "climate change" keyword and select a response related to environment
    if (inputPergunta.value.toLowerCase().includes("climate change")) {
        // Filter responses related to environment
        const respostasEnvironment = respostas.filter(resposta => resposta.toLowerCase().includes("environment"));
        totalRespostas = respostasEnvironment.length;
        numeroAleatorio = Math.floor(Math.random() * totalRespostas);
        elementoResposta.innerHTML = pergunta + respostasEnvironment[numeroAleatorio];
    } else {
        // If no specific keyword is detected, select a random response
        numeroAleatorio = Math.floor(Math.random() * totalRespostas);
        elementoResposta.innerHTML = pergunta + respostas[numeroAleatorio];
    }

    elementoResposta.style.opacity =  1;

    setTimeout(function() {
        elementoResposta.style.opacity =  0;
        buttonPerguntar.removeAttribute("disabled")
    },  4000)
}
